<a href="https://colab.research.google.com/github/nicollcr/Nicoll_CrespoRoncallo_KC/blob/main/SEMANA1/TALLER_SEMANA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Taller SEMANA 1 
**Nicoll Crespo Roncallo**

In [2]:
import numpy as np 
import time

**1.	Tienen el siguiente arreglo:**

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Como es posible obtener el siguiente resultado:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [18]:
# 1. 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
print('-----------Solucion--------------')
arr[1:10:2] = -1
arr

[0 1 2 3 4 5 6 7 8 9]
-----------Solucion--------------


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**2.	Tienen el siguiente input:**

> np.arange(10)

Como se puede hacer para obtener el siguiente resultado:

> array([[0, 1, 2, 3, 4],

>        [5, 6, 7, 8, 9]])


In [17]:
# 2. 
print(np.arange(10))
print('-----------Solucion--------------')
np.arange(10).reshape((2,5))

[0 1 2 3 4 5 6 7 8 9]
-----------Solucion--------------


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**3.	Con base en el siguiente input:**

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Obtener el siguiente resultado: 

 array([[0, 1, 2, 3, 4],
>        [5, 6, 7, 8, 9],
>        [1, 1, 1, 1, 1],
>        [1, 1, 1, 1, 1]])


In [16]:
# 3. 
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2, -1)
print(b)
print('-----------Solucion--------------')
np.concatenate((a, b), axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
-----------Solucion--------------


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**4.	Con base en el siguiente input:**

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Obtener el siguiente output: 

array([2, 4])



In [15]:
# 4
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
print(a)
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(b)
print('-----------Solucion--------------')
c = np.extract(a==b, a)
np.unique(c)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
-----------Solucion--------------


array([2, 4])

**5.	Del siguiente input:**

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Obtener el siguiente output:

array([1,2,3,4])


In [14]:
# 5
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
print(a)
print(b)
print('-----------Solucion--------------')
np.extract((a<5) | (b<5), a)

[1 2 3 4 5]
[5 6 7 8 9]
-----------Solucion--------------


array([1, 2, 3, 4])

**6.	Con el siguiente input:**

a = np.array([2, 6, 1, 9, 10, 3, 27])

Obtener:

(array([6, 9, 10]),)


In [12]:
# 6
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)
print('-----------Solucion--------------')
a[np.where((a>3) & (a<27))],

[ 2  6  1  9 10  3 27]
-----------Solucion--------------


(array([ 6,  9, 10]),)

**7.	Invertir las filas de un arreglo de matriz 2D**

arr = np.arange(9).reshape(3,3)

Output deseado:

array([[6, 7, 8],

       [3, 4, 5],
       [0, 1, 2]])


In [13]:
#7
arr = np.arange(9).reshape(3,3)
print(arr)
print('-----------Solucion--------------')
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------Solucion--------------


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])